Add preimage and disclosure to transaction table
bumi/lightning-browser-extension pull request #229
Opened 2021-09-13 19:26 UTC by lejara

If there are any style changes you like, ill be happy to add

Resolves: #214

2021-09-14 08:54 UTC, bumi commented
great! I think that is perfect! thanks

2021-09-14 09:06 UTC, dylancom requested changes

2021-09-14 09:06 UTC, dylancom commented on src/app/components/TransactionsTable/index.tsx
> +                <>
The "Fragment" can be left out as `<div key {tx.id} />` is already the outer div.

2021-09-15 15:08 UTC, merged

2021-09-15 15:08 UTC, bumi commented
yay, thanks! 🎉